### ISSUE TITLE
Handling intrinsics

### ISSUE THREAD

**Issue by jhnaldo** [kaist-plrg/jiset#101]
6.1.7.4 Well-Known Intrinsic Objects

Added global names: INTRINSIC_<name>

**Comment by yusungsim** [comment]
Bug: ES2021 - Table only contains part of intrinsic object names.
Intrinsic object names that are not in table `sec-well-known-intrinsic-objects` should be parsed with some rule,
and find reference from global names.

**Comment by yusungsim** [comment]
> Bug: ES2021 - Table only contains part of intrinsic object names.
> Intrinsic object names that are not in table `sec-well-known-intrinsic-objects` should be parsed with some rule,
> and find reference from global names.

%TypeErrorPrototype% is not existing in intrinsics table, which appears on manual IRES code.
Changes in manual IRES code is needed.
