### ISSUE TITLE
Debugging of ReferenceChecker for temporal variables 

### ISSUE THREAD

**Issue by jhnaldo** [kaist-plrg/jiset#115]
`ReferenceChecker` detects a temporal variable `__x6__` in `ECMAScriptFunctionObject.Construct`.
However, temporal variables must not be detected in `ReferenceChecker`

**Comment by yusungsim** [comment]
`__x6__` 와 같은 temporal variable이 `ReferenceChecker`에서 오류로 감지되었던 것은 `GeneralAlgoCompiler`에서 `removeStmt` 경우에 6번째 case에 `let`을 붙여주지 않아 발생한 문제.
기타 해결 방법으로는 `ReferenceChecker`에서 temporal variable을 무시하는 방법이 있었으나, 위의 해결 방법 채택.
