### ISSUE TITLE
Not yet extracted helpers

### ISSUE THREAD

**Issue by jhnaldo** [kaist-plrg/jiset#120]
e.g. `GetValue: HasPrimitiveBase, IsPropertyReference, GetReferencedName, GetBase, IsUnresolvableReference, IsStrictReference` in `es2016` version.

**Comment by yusungsim** [comment]
해당 helper가 ES2016, ES2017에만 있는 것 확인 (ES2018부터는 `emu-alg`로 작성됨)

둘 모두 `emu-clause id=sec-reference-specification-type` 태그 아래의 첫 번째 `ul`에 일반 텍스트로 한 줄 씩 정의되어있음.
