### ISSUE TITLE
Detect unused user variables

### ISSUE THREAD

**Issue by jhnaldo** [kaist-plrg/jiset#126]
Implement a checker that detects variables defined by users but never used.

**Comment by yusungsim** [comment]
`UnusedVariable` 과 `UnusedVarChecker` 추가 완료.
syntax-directed algorithm 체크 시 `let somevariable = this` 로 정의한 변수과, syntax production의 rhs에 존재하는 변수?들을 모두 unused variable로 걸러내는 버그 있음.
