### ISSUE TITLE
Unused variable checker - syntax-directed algorithm에서 불필요하게 많은 오류를 잡는 현상

### ISSUE THREAD

**Issue by yusungsim** [kaist-plrg/jiset#133]
i.e. `#sec-module-semantics-static-semantics-exportedbindings`
(`sbt "run check -parse:query=#sec-module-semantics-static-semantics-exportedbindings -parse:detail"` 으로 reproduce 가능)

```
--------------------------------------------------
ModuleItemList[1,0].ExportedBindings (this, ModuleItemList, ModuleItem):
          1. Let _names_ be ExportedBindings of |ModuleItemList|.
          1. Append to _names_ the elements of the ExportedBindings of |ModuleItem|.
          1. Return _names_.
====>
{
  let ModuleItemList = this
  access __x0__ = (ModuleItemList "ExportedBindings")
  let names = __x0__
  access __x1__ = (ModuleItem "ExportedBindings")
  let __x2__ = __x1__
  let __x3__ = 0i
  while (< __x3__ __x2__["length"]) {
    let __x4__ = __x2__[__x3__]
    append __x4__ -> names
    __x3__ = (+ __x3__ 1i)
  }
  app __x5__ = (WrapCompletion names)
  return __x5__
}
--------------------------------------------------
--------------------------------------------------
ModuleItem[0,0].ExportedBindings (this, ImportDeclaration):
ModuleItem[2,0].ExportedBindings (this, StatementListItem):
          1. Return a new empty List.
====>
{
  let ModuleItem = this
  app __x0__ = (WrapCompletion (new []))
  return __x0__
}
--------------------------------------------------
```
결과로 report되는 unused variable error

```
unused variable checking...
[UnusedVariable] ModuleItem[0,0].ExportedBindings: ImportDeclaration, ModuleItem
[UnusedVariable] ModuleItem[2,0].ExportedBindings: StatementListItem, ModuleItem
2 algorithms have unused variable errors.
```

1. `let ModuleItem = this`으로 불필요한 선언을 해서 `ModuleItem`이 report됨
2. production rhs에서 `ImportDeclaration`, `StatementListItem`이 쓰이지 않은 것은 맞으나, 밑의 알고리즘 내용으로 보았을 때 Error로까지 report하는 것은 불필요해보임
  - 2번의 경우 `algo.params`의 모든 변수를 scope에 넣고 checking하기 때문인데, syntax-directed 일 경우 사용되지 않는 변수는 report하지 않는 방식으로 바꿀 수 있음.

**Comment by yusungsim** [comment]
f48cb91419f8353c37ae96e61339a3c0a68572e2
위의 2번의 경우의 불필요한 report를 줄임
algo가 syntax-directed일 경우, 함수 parameter로 선언된 변수는 `SyntaxUnused`로 맵에 저장되어서,
마지막에 unused variable을 report할 때 걸리지 않음.

**Comment by yusungsim** [comment]
6a67ba16a36e968c01d94e6542f85b9dfb14a3a8

위 1번의 경우의 report를 줄임.
`SyntaxDirectedHead`일 경우 `algo.name`에서 `'['`이 시작하는 index까지의 substring을 lhsName으로 받아오고,
`errors`에 lhsName이 남아있을 경우 빼주도록 했음.

여전히 report되는 syntax-directed algorithm이 있어 확인중.

**Comment by yusungsim** [comment]
```
unused variable checking...
...
[UnusedVariable] StatementListItem[0,0].TopLevelVarDeclaredNames: LabelledStatement
[UnusedVariable] StatementListItem[0,0].TopLevelVarScopedDeclarations: LabelledStatement
[UnusedVariable] IsLabelledFunction: FunctionDeclaration
[UnusedVariable] LabelledItem[0,0].TopLevelVarDeclaredNames: LabelledStatement
[UnusedVariable] LabelledItem[0,0].TopLevelVarScopedDeclarations: LabelledStatement
```

위 4개의 경우에 대해 확인해봄.

```
object LabelledItem0TopLevelVarDeclaredNames0 extends Algorithm {
  val name: String = "LabelledItem0TopLevelVarDeclaredNames0"
  val length: Int = 0
  val lang: Boolean = true
  val func: Func = FixUIdWalker(parseFunc(""""LabelledItem0TopLevelVarDeclaredNames0" (this, Statement) => {
    if (is-instance-of Statement Statement10) {
      access LabelledStatement = (Statement "LabelledStatement")
      access __x0__ = (Statement "TopLevelVarDeclaredNames")
      return __x0__
    } else {}
    access __x1__ = (Statement "VarDeclaredNames")
    return __x1__
  }"""), this)
}
```

실제로 `access LabelledStatement = (Statement "LabelledStatement")`와 같이 unused variable이 선언되는 곳이 있음.
ES와 비교해본 결과, (#sec-labelled-statements-static-semantics-toplevelvardeclarednames) ES의 알고리즘에서는 해당 LabelledStatement라는 변수를 선언하지 않음.
IRES로 컴파일 하는 과정에서 verbose한 변수를 선언하는 문제로 생각됨.

**Comment by jhnaldo** [comment]
> [f48cb91](https://github.com/kaist-plrg/jiset/commit/f48cb91419f8353c37ae96e61339a3c0a68572e2)
> 위의 2번의 경우의 불필요한 report를 줄임
> algo가 syntax-directed일 경우, 함수 parameter로 선언된 변수는 `SyntaxUnused`로 맵에 저장되어서,
> 마지막에 unused variable을 report할 때 걸리지 않음.

syntax 뿐만 아니라 모든 parameter에 적용해야 된다고 생각해서 parameter에 대해서는 unused variable checking을 안함

> [6a67ba1](https://github.com/kaist-plrg/jiset/commit/6a67ba16a36e968c01d94e6542f85b9dfb14a3a8)
> 
> 위 1번의 경우의 report를 줄임.
> `SyntaxDirectedHead`일 경우 `algo.name`에서 `'['`이 시작하는 index까지의 substring을 lhsName으로 받아오고,
> `errors`에 lhsName이 남아있을 경우 빼주도록 했음.
> 
> 여전히 report되는 syntax-directed algorithm이 있어 확인중.

이는 여기가 아니라 Compiler에서 해결할 문제인 것 같음
`this`에 대한 handling을 다르게 해서 해결하는 것이 나아보임


> ```
> unused variable checking...
> ...
> [UnusedVariable] StatementListItem[0,0].TopLevelVarDeclaredNames: LabelledStatement
> [UnusedVariable] StatementListItem[0,0].TopLevelVarScopedDeclarations: LabelledStatement
> [UnusedVariable] IsLabelledFunction: FunctionDeclaration
> [UnusedVariable] LabelledItem[0,0].TopLevelVarDeclaredNames: LabelledStatement
> [UnusedVariable] LabelledItem[0,0].TopLevelVarScopedDeclarations: LabelledStatement
> ```
> 
> 위 4개의 경우에 대해 확인해봄.
> 
> ```scala
> object LabelledItem0TopLevelVarDeclaredNames0 extends Algorithm {
>   val name: String = "LabelledItem0TopLevelVarDeclaredNames0"
>   val length: Int = 0
>   val lang: Boolean = true
>   val func: Func = FixUIdWalker(parseFunc(""""LabelledItem0TopLevelVarDeclaredNames0" (this, Statement) => {
>     if (is-instance-of Statement Statement10) {
>       access LabelledStatement = (Statement "LabelledStatement")
>       access __x0__ = (Statement "TopLevelVarDeclaredNames")
>       return __x0__
>     } else {}
>     access __x1__ = (Statement "VarDeclaredNames")
>     return __x1__
>   }"""), this)
> }
> ```
> 
> 실제로 `access LabelledStatement = (Statement "LabelledStatement")`와 같이 unused variable이 선언되는 곳이 있음.
> ES와 비교해본 결과, (#sec-labelled-statements-static-semantics-toplevelvardeclarednames) ES의 알고리즘에서는 해당 LabelledStatement라는 변수를 선언하지 않음.
> IRES로 컴파일 하는 과정에서 verbose한 변수를 선언하는 문제로 생각됨.

Verbose한 것이 아님. ES에 직접적으로 나오지는 않지만 저 pattern으로 변수가 선언된 것 처럼 사용하는 예시가 있음.
