### ISSUE TITLE
Not yet extracted algorithms in Numeric Types

### ISSUE THREAD

**Issue by h2oche** [kaist-plrg/jiset#144]
- Number::exponentiate
- Number::mutiply
- Number::divide
- Number::remainder
- Number::add
- BigInt::bitwiseNOT
- BigInt::mutiply
- BigInt::add
- BigInt::subtract

Then, fix `ECMAScript.PREDEF_FUNC`.

**Comment by ShinWonho** [comment]
위에 언급된 타입들은 모두  emu-alg 태그가 없는 알고리즘이었습니다.
위에 언급된 타입 말고도 emu-alg태그가 없는 알고리즘들이 뽑히지 않고 있었습니다.
