### ISSUE TITLE
handle multiple condition operation

### ISSUE THREAD

**Issue by ShinWonho** [kaist-plrg/jiset#182]
Many conditions are failed, because of multiple condition operation.
ex)
Math.cos
If _n_ is *NaN*, _n_ > *1*<sub>𝔽</sub>, or _n_ < *-1*<sub>𝔽</sub>, return *NaN*.

(condOp is distinguished by either "or" or "and". But "or" or "and" only appears at the last condition operation.)

**Comment by ShinWonho** [comment]
Also consider complex condition
ex)
If IsDataDescriptor(_targetDesc_) is *true*, _targetDesc_.[[Configurable]] is *false*, and _targetDesc_.[[Writable]] is *true*, then

**Comment by ShinWonho** [comment]
If some condition is the following:
"A or B and C or D"
It is interpreted as (|| A (&& B (|| C D))), though the intention is "(A or B) and (C or D)".
ex)
GetOwnPropertyKeys
"If Type(_nextKey_) is Symbol and _type_ is ~symbol~ or Type(_nextKey_) is String and _type_ is ~string~, then ... "
However, it is due to the ambiguity of the spec.

In this example, condition operation is (intentionally or not) interpreted with right associativity.
To solve the above complex, multiple condition, I follow the right associativity for backward compatibility.

**Comment by h2oche** [comment]
Handled in e1354e78b
