### ISSUE TITLE
single stepping through the spec - brief demo video, please?

### ISSUE THREAD

**Issue by dckc** [kaist-plrg/jiset#200]
This work is pretty amazing... especially that debugger tool for single-stepping thru the spec.

Are there any recorded talks of that tool in action?

If not, please consider making a short 3-5 minute video of it.

**Comment by jhnaldo** [comment]
Hi, @dckc. Thanks for your attention to our JISET framework! We only have several recorded academic talks but do not have any recorded talks focusing on how to use this framework yet. We will make it with the single-stepping feature in several months. However, we are currently focusing on refactoring our framework to support new writing styles of ECMAScript specifications including types and other features. When we finish recording the video, I will share the link in this thread. Thank you for the good suggestion!

**Comment by dckc** [comment]
Yay! I see you shared a video:

https://github.com/es-meta/esmeta#ecmascript-debugger
https://www.youtube.com/watch?v=syfZ3v6JNg8 Jan 28, 2022
